# Meeting Recorder Configuration

# Output directory settings
output_dir:
  base_path: "/home/sudonim/Documents/Obsidian Vault"
  meetings_subdir: "meetings"  # Subdirectory within base_path for meeting notes

# Audio settings
audio:
  sample_rate: 16000
  format: s16le
  channels: 1

# Processing mode (v0.4)
processing:
  mode: "hybrid"  # Options: local, remote, hybrid
  # hybrid: Try remote server first, fallback to local on failure
  # remote: Remote only (fail if server unavailable)
  # local: Local only (never use server)

  server:
    enabled: true
    url: "https://firecorn.net:8000"  # Your processing server
    api_key: ""  # Optional API key for authentication
    timeout: 300  # Timeout in seconds for processing (5 min)
    health_check_timeout: 5  # Timeout for server health check (5 sec)

# Transcription settings
whisper:
  model: base  # Options: tiny, base, small, medium, large
  device: auto  # Options: cpu, cuda, auto (auto tries cuda first, falls back to cpu)
  compute_type: default  # Options: default, int8, int8_float16, float16 (int8 is faster on CPU)
  language: en

# Summarization settings
summarization:
  ollama_endpoint: "https://ollama.firecorn.net"
  model: "qwen3:8b-q8_0"  # Higher quality 8-bit quantization for better summarization

# Output settings
output:
  keep_audio: true  # Keep WAV files
  timestamp_format: "%Y-%m-%d_%H-%M-%S"
