# Meeting Recorder Configuration

# Output directory settings
output_dir:
  base_path: "/home/sudonim/Documents/Obsidian Vault"
  meetings_subdir: "meetings"  # Subdirectory within base_path for meeting notes

# Audio settings
audio:
  sample_rate: 16000
  format: s16le
  channels: 1

# Transcription settings
whisper:
  model: base  # Options: tiny, base, small, medium, large
  device: cpu  # Options: cpu, cuda, auto
  language: en

# Summarization settings
summarization:
  ollama_endpoint: "https://ollama.firecorn.net"
  model: "qwen3:8b-q8_0"  # Higher quality 8-bit quantization for better summarization

# Output settings
output:
  keep_audio: true  # Keep WAV files
  timestamp_format: "%Y-%m-%d_%H-%M-%S"
